# Data Management in Python (Instructional Worksheet)

## Packages

The functions in Python are organized in packages or libraries. Packages are install with the `pip` or `conda` commands in the terminal. Once installed then the `import` command is used in python to access the package. 

In [4]:
ly.head()

year     pop
0  1821   269.0
1  1822   321.0
2  1823   585.0
3  1824   871.0
4  1825  1475.0

In [24]:
import pandas as pd   # Loads the pandas package and names it pd

## Importing .CSV and .TXT files

Python can import data stored in a wide variety of file types (including Excel files), but the file type you'll probably encounter most frequently has a .csv or .txt extension. The .csv extension stands for "comma-separated values."

> ### Note: A CSV file is recommended for R.

A .txt file, on the other hand, is a simple text file created with a program like Notepad. Instead of commas, text files often use hidden characters, the tab and newline characters for example, to separate values.

## Read Commands

The following command can be typed into the console to import the data.

For a CSV file:
```
data = pd.read_csv("data.csv")
```

For a text file:
```
data = pd.read_table("data.txt", sep=" ")
```

The first argument is the file name (found within the working directory set earlier). 

The second argument, sep, refers to what is separating the values. A CSV uses commas, but a text document could use semicolons, colons, etc.

# Matrices and Data Frames

## Matrices

Matrices are two-dimensional, for example a 4 x 5 matrix has 4 rows and 5 columns. All values within the matrix must be of the same type, i.e., all numeric or all characters 

In [25]:
import numpy as np

mymatrix = np.array([[1,2], [3,4]])
mymatrix

array([[1, 2],
       [3, 4]])

In [26]:
mymatrix[0,1]  # The value in row 1 column 2
mymatrix[1,0]  # The value in row 2 column 1
mymatrix[:,1]   # The values for all rows, column 2
mymatrix[0,:]   # The values for row 1, and all columns
mymatrix[[0,1],:] # The values from row 1 to 2, and all columns

array([[1, 2],
       [3, 4]])

In [27]:
mymatrix[0,1] = 0
mymatrix

array([[1, 0],
       [3, 4]])

## Data Frames

Data frames are the workhorses of Python/Pandas and are a more general form of matrix. The values do not have to be of the same type, but instead one data frame can contain numbers, characters, and factors.

In [28]:
d = [1,2,3,4]
e = ["red", "white", "red", "blue"]
f = ["high", "low", "high", "high"]

mydata = pd.DataFrame({"ID" : d,
                      "Color" : e,
                      "Level" : f})

mydata

ID  Color Level
0   1    red  high
1   2  white   low
2   3    red  high
3   4   blue  high

The values of a data frame can be accessed in a variety of ways.

In [35]:
mydata.iloc[:,0]    # Calls column 1
mydata["ID"] # Another way to access column 1 - using the column name
mydata.ID    # Last way to access column 1 - also using the column name  
mydata.iloc[0,:]   # Access the first row

ID          1
Color     red
Level    high
Name: 0, dtype: object

## Useful Functions for Data Sets

R has a lot of built-in datasets that we will use throughout the course. If you use *data()* you can see a list of all available datasets. In this case we will use the Loblolly dataset, which contains growth information about a set of Loblolly pine trees. We can use this below to import R datasets into Python.

In [36]:
from rpy2.robjects import r, pandas2ri
def data(name):
    return pandas2ri.ri2py(r[name])

Loblolly = data('Loblolly')

/home/greg/anaconda3/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py:191: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  res = PandasDataFrame.from_items(items)


In [37]:
Loblolly.info() # Structure of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 3 columns):
height    84 non-null float64
age       84 non-null float64
Seed      84 non-null category
dtypes: category(1), float64(2)
memory usage: 2.2 KB


In [39]:
Loblolly         # Displays all the data
Loblolly.head()  # Displays first 6 rows of data
Loblolly.tail()  # Displays last 6 rows of data

height   age Seed
79    9.05   5.0  331
80   25.85  10.0  331
81   39.15  15.0  331
82   49.12  20.0  331
83   59.49  25.0  331

In [41]:
len(Loblolly)      # Number of rows
len(Loblolly.T)    # Number of columns

3

For many variables in Python you can use the `.T` to transpose the matrix or data frame you are working with.

In [43]:
len(Loblolly.age)  # Number of data points in that column

84

## Subsetting Data

Sometimes if we have a large dataset for multiple categories, we might want to subset it into smaller datasets for analysis.  

For example, let's look at the Loblolly dataset, which gives us information on the height and age of loblolly pine trees from different seeds.  

We can create separate datasets for each of the seeds.   

In [45]:
# This creates a new dataframe called 'seed301' which contains all columns of data 
# for just the seed numbered 301
seed301 = Loblolly[Loblolly.Seed == '301']
seed301

height   age Seed
0    4.51   3.0  301
1   10.89   5.0  301
2   28.72  10.0  301
3   41.74  15.0  301
4   52.70  20.0  301
5   60.92  25.0  301

In [47]:
# This dataframe only contains the data on Loblolly trees 
# at less than 5 years of age (only the trees at 3 years of age)
Loblolly2 = Loblolly[Loblolly.age < 5]
Loblolly2

height  age Seed
0     4.51  3.0  301
6     4.55  3.0  303
12    4.79  3.0  305
18    3.91  3.0  307
24    4.81  3.0  309
30    3.88  3.0  311
36    4.32  3.0  315
42    4.57  3.0  319
48    3.77  3.0  321
54    4.33  3.0  323
60    4.38  3.0  325
66    4.12  3.0  327
72    3.93  3.0  329
78    3.46  3.0  331

## Merging Data Frames

Sometimes you need to merge two dataframes using a column (variable) that is shared between them.  

Let's create two small dataframes and then we can merge them based on the shared column.

In [53]:
dataA = pd.DataFrame({"year" : list(range(2000,2006)),
                     "v1" : [1,5,3,4,2,2]})
dataB = pd.DataFrame({"year" : list(range(2000,2006)),
                     "v2" : [2,4,3,5,5,5]})

In [56]:
comb_data = pd.merge(dataA, dataB, on='year')
comb_data

year  v1  v2
0  2000   1   2
1  2001   5   4
2  2002   3   3
3  2003   4   5
4  2004   2   5
5  2005   2   5

# Problem Set

1. Open the 'PlantGrowth' built-in dataset.  

2. Display the structure of the PlantGrowth data frame. What is included? How many observations and how many variables? What are the variable names?  

3. What are three ways to display the data in column 1 of the PlantGrowth data frame?  

4. How do you access the $5th$ row of data in the PlantGrowth data frame?  

5. Display the first $5$ rows of the PlantGrowth data frame.  

6. Display the last $5$ rows of the PlantGrowth data frame.  

7. How many rows are in the PlantGrowth data frame?  

8. How many columns are in the PlantGrowth data frame?  

9. Look at the group column for the PlantGrowth data frame. How many options are there? Create a new data frame (called ctrl) that contains the data only for the 'ctrl' group.  

10. Create a new data frame called GrowthHigh that only contains the data when the weight is over $5.50$. How many rows are in this new data frame? 

In [58]:
PlantGrowth = data('PlantGrowth')

PlantGrowth.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
weight    30 non-null float64
group     30 non-null category
dtypes: category(1), float64(1)
memory usage: 454.0 bytes


/home/greg/anaconda3/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py:191: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  res = PandasDataFrame.from_items(items)


In [62]:
PlantGrowth.weight
PlantGrowth['weight']
PlantGrowth.iloc[:,0]

0     4.17
1     5.58
2     5.18
3     6.11
4     4.50
5     4.61
6     5.17
7     4.53
8     5.33
9     5.14
10    4.81
11    4.17
12    4.41
13    3.59
14    5.87
15    3.83
16    6.03
17    4.89
18    4.32
19    4.69
20    6.31
21    5.12
22    5.54
23    5.50
24    5.37
25    5.29
26    4.92
27    6.15
28    5.80
29    5.26
Name: weight, dtype: float64

In [63]:
PlantGrowth.head()
PlantGrowth.tail()

weight group
25    5.29  trt2
26    4.92  trt2
27    6.15  trt2
28    5.80  trt2
29    5.26  trt2

In [64]:
len(PlantGrowth)
len(PlantGrowth.T)

2

In [68]:
ctrl = PlantGrowth[PlantGrowth.group == 'ctrl']
ctrl

weight group
0    4.17  ctrl
1    5.58  ctrl
2    5.18  ctrl
3    6.11  ctrl
4    4.50  ctrl
5    4.61  ctrl
6    5.17  ctrl
7    4.53  ctrl
8    5.33  ctrl
9    5.14  ctrl

In [67]:
GrowthHigh = PlantGrowth[PlantGrowth.weight > 5.5]
GrowthHigh

weight group
1     5.58  ctrl
3     6.11  ctrl
14    5.87  trt1
16    6.03  trt1
20    6.31  trt2
22    5.54  trt2
27    6.15  trt2
28    5.80  trt2